#!/usr/bin/env bash
# Usage: bash-trash put filename [filename...]
# Summary: Put files in the trash
# provide bash-trash completions
set -euo pipefail
if [[ -n "${DEBUG:+1}" ]]; then
	set -x
fi

if [[ -z "${1:-}" ]]; then
	bash-trash-help put >&2
	exit 1
fi

if [[ "${1:-}" == '--complete' ]]; then
	shift 1
	for item in $(compgen -o default); do
		if [[ -d "${item}" ]]; then
			echo "${item}/"
		else
			echo "${item}"
		fi
	done
	exit
fi

_bash_trash_put() {
	local filename
	filename="${1:?usage: _bash_trash_put <path>}"
	filename="$(abs_path "${filename}")"

	local trash_dir="${HOME}/.local/share/Trash"
	local trash_files_dir="${trash_dir}/files"
	local trash_info_dir="${trash_dir}/info"

	if [[ -d "${trash_files_dir}" ]]; then
		mkdir -p "${trash_files_dir}" || return 1
	fi
	if [[ -d "${trash_info_dir}" ]]; then
		mkdir -p "${trash_info_dir}" || return 1
	fi

	local trash_filename="${filename##*/}"
	if [[ -e "${trash_files_dir}/${trash_filename}" ]]; then
		i=1
		while [[ -e "${trash_files_dir}/${trash_filename} (${i})" ]]; do
			((i++))
		done
		trash_filename="${trash_filename} (${i})"
	fi

	mv "${filename}" "${trash_files_dir}/${trash_filename}"

	cat >"${trash_info_dir}/${trash_filename}.trashinfo" <<-EOF
		[Trash Info]
		Path=${filename}
		DeletionDate=$(date +'%FT%T')
	EOF
}

for filename in "${@}"; do _bash_trash_put "${filename}"; done
