#!/usr/bin/env bash
# Usage: bash-trash restored [filename...]
# Summary: Restore trash files from the current or any child directories
set -euo pipefail
if [[ -n "${DEBUG:+1}" ]]; then
	set -x
fi

if [[ $# -gt 0 ]]; then
	for filename in "${@}"; do bash-trash restore "${filename}"; done
else
	bash-trash lsd --no-fzf |
		fzf -i -e +s -m --bind=ctrl-o:toggle-all --header "Tab: toggle, C-o: toggle-all" |
		while read -r line; do bash-trash restore "${line}"; done
fi
